"""Add Profile and Experience models

Revision ID: 0282962e9baa
Revises: 3c45e79180a3
Create Date: 2025-10-07 13:27:40.672530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0282962e9baa"
down_revision: Union[str, Sequence[str], None] = "3c45e79180a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=True),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("contact", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("draft_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("profile_photo_url", sa.Text(), nullable=True),
        sa.Column("completeness_score", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_profiles_slug"), "profiles", ["slug"], unique=True)
    op.create_table(
        "experiences",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("profile_id", sa.String(length=26), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("company_website", sa.String(length=500), nullable=True),
        sa.Column("company_size", sa.String(length=50), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("company_location", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=200), nullable=False),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsibilities", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("technologies", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("experiences")
    op.drop_index(op.f("ix_profiles_slug"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
